apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coroot
  namespace: flux-system
spec:
  interval: 24h
  url: https://coroot.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coroot
  namespace: flux-system
spec:
  releaseName: coroot
  targetNamespace: coroot
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: coroot
      sourceRef:
        kind: HelmRepository
        name: coroot
        namespace: flux-system
  values:
    corootCE:
      service:
        type: ClusterIP
        port: 8080
    clickhouse:
      fullnameOverride: "coroot-clickhouse"
      image:
        repository: bitnamilegacy/clickhouse
        tag: "latest"
  valuesFrom:
    - kind: Secret
      name: coroot-secret
      valuesKey: admin-password
      targetPath: corootCE.authBootstrapAdminPassword
