apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: home-subnet-router
  namespace: tailscale
spec:
  tags:
    - tag:k3s
  subnetRouter:
    advertiseRoutes:
      - "10.100.102.0/24"
