apiVersion: v1
kind: Secret
metadata:
    name: gokapi-bootstrap
    namespace: gokapi
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:BhvBoy72uz9Q+fw3P7xBaVCiAFrFEWkeFeEHUD/msy0jEmiraVq/suoJ8aBTy9+0fjckiUBqOHqAksNSopR3QR/kIh7ETCiwTlq0Y2MAOAruqI0ikfRmzif3fLKU2D5WwtM/o/Vob952v1eEQNFIJA7ZmbMsBJmDkoUuIJHDjFLf98g1O8oDIjUJnSc/7tg+Il69WHD7vnU7JUDg0x691mLmVjvGL2/gn8cG6C8HzWTXJKANWhZ5cSlK/kkatQDxanZHml+q9Dzht2dIOymtilMHNC6ZeKQEnT5xYjYIRHfgFfRfa0szNSe7rhPr26ex9ws2kjXehqohJifhM+HkI2j8XFyFZI7iTMQObDX+AOHETiUSohoOmg/N1//0Hw7caY+8ET9rvLou1+Xmb8FVT0Aq6CfK+tzHeRdKJL3phmYNt4zYbzHt4sefdgk++MGMrB7sXj5TdkKstt7BEIqHTbm7ZvA3mKypOc/Sg5gurfJGULB6Gl4wai7BkHek2CRoS1et3QHLyJbqW5Zw1AzIsJ2CG53UPNHhPoyfpzj1d6FhRIkKLmNcE6r6Ju+UhCMqaNHJlNsX5Cg9HWK/ibWPbkRb8r+3EEZF9smgGdmw72qN8zogABZNsth+5EFPMc1pLY4woPO8XdtJJuMc57LZDjHZzb5uhBrKSBrk0EnKdX1Muktla8zvf+EQkDvi/z8Zdg3nkZCpiksz3EeymfxruBXN/HkBmSMKWg9plZH64OGX/NSN+/1mgDX3J1fDJtMnTlzWR2BpiL8tFCRtqrTOvpLd4CBYQHP1h+g4YtnVc1hemLrklKDZFtfsMi+j8yHBKHniL8VlC6zlEyiYwl9e4l19JOwepiQTB486+yoy/CsTqhZ+a4GH6sIxqA25GLQMfl/vPmND69Gxe6Lh9rxo4gN3WJ0aQHmMCOVnoyFwMBkU9z5BnqD0xBaxc7Hx761PCei970+8yFI7PG5wgRmOTi5SG9YDfgoDkUHH1RJdQj/l6C97QE+CTwlekA==,iv:84uAR2eJ558dL/cyPcsOKlO2wUNybGe2o1w2GLsRACg=,tag:JbMUmIQiLFNT6NVWc/bEKQ==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:dHFXMoWPe1ZJfw==,iv:W0Q++7b8lSWV7/Fa7Rx8Koq0i2OOVNiPMph7LltpZWQ=,tag:ikRhH3QALzL4TrTLfuwIFw==,type:str]
    basic-auth-hash: ENC[AES256_GCM,data:NhZARj1VJl5R2FVKwGAqfOJrduKm1oiXsJd3fmXVQVs9VVxoujEkHZKky3fJ+wZHrIlCVQtt4uV/ofTu,iv:kUQhQmq/oHd32oIw30GPD773fXkW6HAhhc2XMGWDAgU=,tag:Jyj1ccTzbvAiOFlcArnzOA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aXlLTnNLWElUSUlSWW1v
            TnpYcGhqaG9SU1ZXdktTbEdwRUpzNlFBSDBFCmFWVkxIZXlnVkZOY1B6RG1tL1dZ
            U0R1VE1XcXFiTkxJY0p1Wk5McmRieDgKLS0tIDlpUEI3MlRCZVhldXZFRXZCNm9B
            VWpQZnd0YWRHWlQ4VG1rTnZYbjIrWmcKmGzmkcBUpa4IKSUF6/hKPNb7QvuVRbAX
            mgF0wRZz+AWF5p8maLcrtUWVQNd1D18o3r7MQIAdkvApwmg4NBgMfg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gvu3dxtasgyejn63ug9yr3yj5n5e28fd4wueawk6p2xdhdm3marq84hu8r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T12:02:54Z"
    mac: ENC[AES256_GCM,data:AOVRZr5joLVbQ7+OtvBpoqNZCoG90NecDh3wmzzamsVu68Rt4MbIa58+4G+TpppmM1LnNbApzJEAQZm7LTDo0kuGqRLCCQZ9tgkLSn7JcA68sD/ycYjYtYVrBOXECXDTiu2C+cbjv60cbDd96k3jfqzM12zOtBEDGoeJ8vxXbdY=,iv:XVe4Z9N+G7Skv/DZ3d7dufUKAnpYlh3ibdfrya5kFXA=,tag:cjGuEif4Fhv9fuBn9mnLdQ==,type:str]
    version: 3.13.3
