apiVersion: v1
kind: Secret
metadata:
    name: gokapi-bootstrap
    namespace: gokapi
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:LTvoyWzI/KfxpbxbqWAERhT8phZKZ0NRY5nIYlD0sO1mEwhzYL72imk/ZNKXMfUchUxuU0sKElcUGrGtEDrBNsbKvrqJGgJ4r0VqUxV7CS5t9rDsP24Be3yk8bH9Z7owm8psIgyEA+TucI8yByBUanA0j0n92lpFiNrG1nZDW+4O6cPvT6YPWWH4/2Nj2f00Kbp5PtHJOXX8P08gVh5Ka9O4FRg0QvBGvfn8ewZbygioQDK6cM8blJsT3X/bEe7jwAcSqZ4CQvMjgK6jODTj0C5Md/QezhpdPwvghWK1Zrjf5fwswHStNX+soF8ASuW/DTP18nRIEDTsfwubhQpwYTeUJLUoHyHvNLkhPzJG9Vl018FY1IFr4Neb1eJDKsB0JOpgxf0BP+d/+xr3h+kWcohZ5kwVjO6lDoFtIwp36NG8KVewonofOCnwU2lplqwfApbRSjI6CIOnVjG0TUxq1A8XkOuAtJtAtq9j0tPVQzg+QpxB+QiXx9UgHCV2Cv0epuC35ybWLj08NqKiGWO2RPL1aVbGziWDrbFUBEJGf9dXEGbLAFDQgKnJqy6C+XF3x+9uSiTaapDfA+M+oMjdyuc79Tfmd/boBrZK0aA13piuTFA0RD/7IFiwMMsFTU9tL1MSvni4JnGy4Q9dnwp4tWTn1p+DqtCdbxsftEZvl9tTNSxPLawknVIZQoFEowlGVRuD37O2DwVPKw71oAReF68gx36irSZuBab16WXiYrYFoscoRvvw/SjONY/XlpPCDAbzi9FtvkgIC1l4bLO98lNyZ64csiZVOsahdYna398tYmGnjpI1BSoFUr6ey0X+6QT/ZBQcV5f37eH1jyOyjiCj89KU2sSS7CVAJ+uaHWbtwESR4/+sYtO/3ud9g61TfQKAtQH071ggF7YjuBXGvGMsOf0IXnhIB5J1WWYMJ6pmmdkjrqz+XrJH1eKbf1vW0MH64ZEIc15InwXnORU40s+IxiNq5qFX4gkGJ97LTciaiMIkOsnOVGvYpg==,iv:s7XqZZPaDoZeDV01ybc1eFkULb6W7XcIZKRXvq4noG8=,tag:Ap7SBaENFoBycVXqri7m7A==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:8TtC3H1tyC49+Q==,iv:4lsUiUpffFgwvOVK4wtyi2jJIy+PANTZr7ES+kK3EGk=,tag:pwzlsBctNw9XaHLCbvIDnw==,type:str]
    basic-auth-hash: ENC[AES256_GCM,data:OUfftXPmKIeA1aiLfWEjWSh0ELUyH2FL15Y58T9IqLepcsd7eAeZLvCC+tF77rLGTh7u9/3e5yTJE5bG,iv:1YnMPShYirVv08YyuaNZrzFrGLrypPOsi7ViKGaw5Zw=,tag:N/c0WK71r6hJdU6oK+turw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQVFlc3NZM1FET0hJc1c5
            alFQMUV2MU9Td3BZUW9ZbFZuZms3WEZGWmpRCjJiZ2lRb0lJWWVrTTdhbjdHSWhu
            Z1RrZUtRc2JqZDQraW9jMExIQlZVNkUKLS0tIGxEQ2M0Y2N1Uk5GN3gyQjVhVHV3
            TXhtRFk3QXUvaFBjQjErcCtLOVNYYVUKMHEIcZ7hcic517FfqvYsIPPGf6JXpLIj
            sfdUj5A7u/Dzp2ru+jgXssVTbZbH4rj3huopKCvb8FSRd0/x4k+TZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gvu3dxtasgyejn63ug9yr3yj5n5e28fd4wueawk6p2xdhdm3marq84hu8r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T12:11:24Z"
    mac: ENC[AES256_GCM,data:bUPW2riKaU/QhUrmL6Ei7rnajWZe7w9eVoLVfTJbVR0R3wliZZf+HXdRFoALm5+1RD+YN7fGK7HRX/8ksJMRPuz5Vg5kRp+fHbNGctSeev0jCoq0SkmD4yTuLBod2owghHs3Q6MK/Zf/CEEJEtcWss5RMSZnrj7Ej9Peu+2TeZg=,iv:kZhTO/eJ6Rs7bFgeQOUy4Eup+8n5u57wgmov00zMVGc=,tag:FHr3vOKJJEVrtHuKGhBTSw==,type:str]
    version: 3.13.3
