apiVersion: v1
kind: Secret
metadata:
    name: gokapi-bootstrap
    namespace: gokapi
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:Ki4aDt+sCnhBUpaRTD4RZa5KV/arDHY0Eh1YRJ0RPMlIwiksYyVZDMOqpkKKN2pOLytMUYafNgNnyYdoBWj9nvyfv9aJWfVAAXDQAuDDsIVnylnsPvlu09F7S0ub+AqReYNGVU/UAoGa6Z+Qwa556AWJtXmgO44hbMFq1VOPpwoVjCdbEZuQ0B+gewAKUSIOVfGVhd7e5OVABLdZgUmRaYeePpRupUUvvrvemrKWgKKbwcXAkk58KGbONuNDM9mcLhnQ3VTpYJPY0UrDIDl8/b0DD0WUBgyKAMkb4ESL2qC6WCANGqX21NE1TTCKgCGUrKJMzlwge9k7G9T1385VEg+hRrkIwz7ZsEyMgVLJ7BTPEN/nqGkDWwlbcBBIBuktTXbMzb6HzGqZ5W09rPIcrdXDhSvSrvilgsSe2d8NrVVnfikP5mpb/y6Z94uYcFA9tbM8vgnCnK8I4T2Lgyv03hpOjUKuUqpRsenyRLuUgiZ6G71jaU6hbX1+XaNiryrFjmgdesCKVJBbZaCU84eUf3IE05HoQohp6LeSel6o3caHF4jBNa99VJ9GmQkwKy/jXRFX/dE0OAS5AC5BCHYsvF7Sg0RuYFXZoOMauJxZGee1LT4HUK8srWwzUdtl9mgcD9+uQuiRDhqIwYL0biTFYimdR8ZbHCmy5tzYgzd8CfqfkWaIEzc61p3yGEhUnz6a9JUEY0zAC5dOR+YD4flYerSgkkM5OBv6X/S8dH4glMkR1bhUZEdv64IiYTvvhwQfardXeqMFhG1s+2qAsGBiCdIiwmMN3bu72VPk5DEZhSuJImxqa2mpmlVfnTYCZYB4HQu1ZtVkMdRJtHMMvWdJHt84h1asDToixdXQElCivQ5kBstOl3tyLYi+dHHiaJ/rwAqiPPqtHllPM4BCXACazCpwLCcocbEIL9LN8+HWhUX/oCLYljPvetyYV/2LWd9SWneHzeNZleE/yIhH1o3W4Sy/AFpODSLwwuRAvH6FQb12us9KTW6W+/ZR4g==,iv:EO2lz/SFpWJP/xscWSYuWU31G2QPPGHnlwInZCdbfQk=,tag:7u4B88B4GwkeaqaeypITxg==,type:str]
    bootstrap-password: ENC[AES256_GCM,data:0Zu51RuHxESz1+SXrBt7dX/bCd2lHt+4eF3yWqe3xbM=,iv:pjhoQfCYz5GADTantngQqHi2zpzB7NadASNPmpSBTJA=,tag:+3UekbKY5285tD1qZh7Uuw==,type:str]
    basic-auth-hash: ENC[AES256_GCM,data:SgzSeNb1luX2uJmp1dUpJ7kVzgaL78lUUiHbz8yiUok+Xth1Cnq6JtVqGr+BcJMsEoTytwXu3Jab+mNx,iv:9CpS2PoDJz+m25HK9C8D/ZZGG3VYNfJ2Ep2D6wcDArw=,tag:I05dHtcCgME2iiA7SPqKKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUQlJiY1hvWDJoQm1WM05I
            NzBqeEdvZVpsOHg2cmNqT1cwZlBUQ3YvWFZzCmRWU1IvUzdVdUxNZnB0RGdqSGYy
            OVJQa2FTZ1JhdG9rRmpkWXRBWUUxZTQKLS0tIGZUYzFEaW5vTENLQXBKMjRTVGpK
            OUJSRXAxcmxubUtxNXRTWm4wUnBjUVEKMrDFXVlIN3Mx4e/L/YBHAIM/y4mbGm/g
            W2+1ald98TrRPmU3tudOkvdQ2hKpb/rKGmcPSQknVnahRvL+qva6aA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gvu3dxtasgyejn63ug9yr3yj5n5e28fd4wueawk6p2xdhdm3marq84hu8r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T11:36:18Z"
    mac: ENC[AES256_GCM,data:6d8v+/qgJS6t+2ZGr3aW1kbIO6p1uE0jgTf+ExtRJdsEnagepW3wBF5hHEQ1hVBAevUNd0Rl0hKPpeFSsn1Lk4co6FhlMq3FqvyqjRmhm4vIxFrRWE0ES7G2BfKYpzSFuq84Qbct8zihhvz2li6cNnxXN5bUuyAQAXBFpHcw4pQ=,iv:QPOxoPUHxQksSGGsvll/NCQbFIYguDoEMOTfg+pmCf8=,tag:ZqEHNI8Sw4Se7oQRwQkh8g==,type:str]
    version: 3.13.3
