apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/audiobookshelf
  - ../base/twofold
  - ../base/homepage
  - ../base/qbittorrent
  - ../base/radarr
  - ../base/jellyseerr
  - ../base/vpn-orchestrator
  - ../base/prowlarr
  - ../base/recyclarr
  - ../base/byparr
  - ../base/sonarr
  - ../base/bazarr
  - ../base/plex