apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https-jellyfin
      protocol: HTTPS
      port: 443
      hostname: jellyfin.firilov.dev
      tls:
        mode: Terminate
        certificateRefs:
          - name: jellyfin-firilov-dev-tls
            namespace: envoy-gateway-system
      allowedRoutes:
        namespaces:
          from: All
    - name: https-radarr
      protocol: HTTPS
      port: 443
      hostname: radarr.firilov.dev
      tls:
        mode: Terminate
        certificateRefs:
          - name: radarr-firilov-dev-tls
            namespace: envoy-gateway-system
      allowedRoutes:
        namespaces:
          from: All
