affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s2
tolerations:
  - key: node.kubernetes.io/unreachable
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 60
  - key: node.kubernetes.io/not-ready
    operator: Exists
    effect: NoExecute
    tolerationSeconds: 60

env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: firilov.dev
  - name: TZ
    value: Asia/Jerusalem

config:
  settings:
    title: Firilov Dev
    background: 
        image: https://w.wallhaven.cc/full/4v/wallhaven-4vw5v8.jpg
        blur: sm
        saturate: 50
        brightness: 50
        opacity: 80
    useEqualHeights: true
    headerStyle: clean
    quicklaunch:
        hideInternetSearch: true
        showSearchSuggestions: false
        hideVisitURL: true
        provider: google
    hideVersion: true
    layout:
      - Media Servers:
          style: row
          columns: 3
      - Media Management:
          style: row
          columns: 5
      - Development:
          style: row
          columns: 1

  services:
    - Media Servers:
        - Plex:
            icon: plex
            href: https://plex.firilov.dev
            description: Media Server
        - Jellyseerr:
            icon: jellyseerr
            href: https://jellyseerr.firilov.dev
            description: Media Requests
        - Audiobookshelf:
            icon: audiobookshelf
            href: https://audiobookshelf.firilov.dev
            description: Audibooks Server
            
    - Media Management:
        - qBittorrent:
            icon: qbittorrent
            href: https://qbittorrent.firilov.dev
        - Radarr:
            icon: radarr
            href: https://radarr.firilov.dev
        - Sonarr:
            icon: sonarr
            href: https://sonarr.firilov.dev
        - Prowlarr:
            icon: prowlarr
            href: https://prowlarr.firilov.dev
        - Bazarr:
            icon: bazarr
            href: https://bazarr.firilov.dev

  bookmarks:
    - Development:
        - GitHub:
            - icon: github
              href: https://github.com/AlexFirilov?tab=repositories