env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: firilov.dev
  - name: TZ
    value: Asia/Jerusalem

config:
  services:
    - Media Management:
        - Jellyfin:
            icon: jellyfin
            href: https://jellyfin.firilov.dev
            description: Media Server
        - Jellyseerr:
            icon: jellyseerr
            href: https://jellyseerr.firilov.dev
            description: Media requests
        - qBittorrent:
            icon: qbittorrent
            href: https://qbittorrent.firilov.dev
        - Audiobookshelf:
            icon: audiobookshelf
            href: https://audiobookshelf.firilov.dev
        - Radarr:
            icon: radarr
            href: https://radarr.firilov.dev
        - Sonarr:
            icon: sonarr
            href: https://sonarr.firilov.dev
        - Prowlarr:
            icon: prowlarr
            href: https://prowlarr.firilov.dev

    - Infrastructure & Ops:
        - Coroot:
            icon: coroot
            href: https://monitor.firilov.dev
            description: Observability
            
    - Automation & Tools:
        - n8n:
            icon: n8n
            href: https://n8n.firilov.dev

bookmarks:
    - Development:
        - GitHub:
            icon: github
            href: https://github.com/AlexFirilov?tab=repositories