apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: recyclarr
type: Opaque
stringData:
    SONARR_API_KEY: ENC[AES256_GCM,data:ZIraYciZpn08/quOrr+F6FuKlTWAtClDyHB2rZwerOI=,iv:kfc68M5aV6A1+cB57ixtRziK2QUOhnqVQppTD80mkDc=,tag:6Oq2co45d/rTTl+3AfS0Fg==,type:str]
    RADARR_API_KEY: ENC[AES256_GCM,data:McYc5Z4ydM1DkVgXDlPedwFHCBDhGKx0Z29gf79pTJY=,iv:oZRMBx/hMEZs1GFABuoQE1ystFg/RfES9AdCsdc9vZA=,tag:7kGU/1d35So+ZCvYBQL+VA==,type:str]
sops:
    age:
        - recipient: age1gvu3dxtasgyejn63ug9yr3yj5n5e28fd4wueawk6p2xdhdm3marq84hu8r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMElvK3BFZElLL2I0Z05C
            cUl0OERacDMzcDlwc3BVS3BhZldBMTUzVzNRCnc4YkZWVWVDWUhDVkJTby9XSlBq
            ZU80RVIxdS8zdzdMbEgxNzZxK0VJQlkKLS0tIGp0MFg5dTRkQ0tGN2M2bXQwdHFs
            VmNQNTVtdm5wbXVqRTI5dVJSc08zT1kK1xm8iCgYkbLGAQNsu1fny4bs2la2p1vK
            IUW2YRZhHA3HMLAV2DxQURrl0BCKvFuhJgYLP2lnRmYISuO90Km3pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T11:42:44Z"
    mac: ENC[AES256_GCM,data:v9Yy8CsxOLIoPQaG+bu2/zOBs+pNO9mMn+zJFKbGAA8eDdYEUaxfrGBOVPFfM/a02QwtIWYBi/doBvbWNcEjQEaB0jgk+uToBMOMpoUTNmSpNixBxTDWOOU5eIkM8QYonnq/AvcrKBpyEluqah4AvfGJWe4B0LkYcOhrZM4LV64=,iv:m0Kr3r/nfqCyiQDtbSAjTa6g8AbFUWPYEa1Np1SUZeE=,tag:CdT1+6SH6S9GPx8kOWHGEQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
