apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  capacity:
    storage: 393Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: plex
    name: media
  nfs:
    server: 10.100.102.54
    path: /mnt/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 393Gi
  volumeName: plex-media
  storageClassName: ""
