apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-media
spec:
  capacity:
    storage: 393Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: plex
    name: media
  hostPath:
    path: /mnt/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: plex
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 393Gi
  volumeName: plex-media
  storageClassName: ""